### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Razzeee** [paulcbetts/electron-spellchecker#8]
When running ```npm install --save electron-spellchecker```
I end up with this in the npm-debug.log:

```
1782 verbose stack Error: @paulcbetts/spellchecker@4.0.3 install: `node-gyp rebuild`
1782 verbose stack Exit status 1
1782 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
1782 verbose stack     at emitTwo (events.js:106:13)
1782 verbose stack     at EventEmitter.emit (events.js:191:7)
1782 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
1782 verbose stack     at emitTwo (events.js:106:13)
1782 verbose stack     at ChildProcess.emit (events.js:191:7)
1782 verbose stack     at maybeClose (internal/child_process.js:852:16)
1782 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
1783 verbose pkgid @paulcbetts/spellchecker@4.0.3
1784 verbose cwd D:\projects\desktop
1785 error Windows_NT 6.1.7601
1786 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "electron-spellchecker"
1787 error node v6.3.1
1788 error npm  v3.10.3
1789 error code ELIFECYCLE
1790 error @paulcbetts/spellchecker@4.0.3 install: `node-gyp rebuild`
1790 error Exit status 1
1791 error Failed at the @paulcbetts/spellchecker@4.0.3 install script 'node-gyp rebuild'.
1791 error Make sure you have the latest version of node.js and npm installed.
1791 error If you do, this is most likely a problem with the @paulcbetts/spellchecker package,
1791 error not with npm itself.
1791 error Tell the author that this fails on your system:
1791 error     node-gyp rebuild
1791 error You can get information on how to open an issue for this project with:
1791 error     npm bugs @paulcbetts/spellchecker
1791 error Or if that isn't available, you can get their info via:
1791 error     npm owner ls @paulcbetts/spellchecker
1791 error There is likely additional logging output above.
1792 verbose exit [ 1, true ]
```

**Comment by paulcbetts** [comment]
You clipped away the part of the log that tells us why it failed

**Comment by Razzeee** [comment]
I was able to solve that problem by adding an entry for repository to my package.json
But now I get this:
http://pastebin.com/wyfj183B

**Comment by paulcbetts** [comment]
Installing native modules is somehow broken on your machine

**Comment by Razzeee** [comment]
I get this on two systems one win7 the other win10, any pointers how to fix this?

**Comment by CompRider** [comment]
Any update?
